version: '3.8'
services:
  db:
    image: postgres:13
    container_name: movie-app-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movieapp
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
